version: "3.8"

services:
  echo-backend:
    build: ./backend
    container_name: echo-backend
    restart: unless-stopped
    # ports:
    #   - "127.0.0.1:8080:8080" # Not needed, internal network only
    environment:
      - GIN_MODE=release
      - PORT=8080
      - GROQ_API_KEY=${GROQ_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - AUTH_USERNAME=${AUTH_USERNAME:-admin}
      - AUTH_PASSWORD=${AUTH_PASSWORD:-admin}
      - STORAGE_PATH=/app/storage
      - DATABASE_PATH=/app/data/echo.db
    volumes:
      # - echo-data:/app/storage # Old docker volume
      - /mnt/nas:/app/storage # New NAS mount (Audio)
      - echo-db:/app/data # Local Volume (Database)
    networks:
      - echo-network

  echo-frontend:
    build: ./frontend
    container_name: echo-frontend
    restart: unless-stopped
    ports:
      - "8000:80"
    depends_on:
      - echo-backend
    networks:
      - echo-network

networks:
  echo-network:
    driver: bridge

volumes:
  echo-data:
  echo-db:
